import FAQAccordion from './FAQAccordion';
import Icon from './Icon';
import { modalityConfig } from './verifierConfig';

const capabilities = [
  ['text', 'Text Verification', 'Analyze messages, articles, and claims for scam, AI-content, and verification signals.'],
  ['image', 'Image Verification', 'Review images for potential manipulation patterns, metadata anomalies, and embedded text.'],
  ['video', 'Video Verification', 'Inspect sampled visual and temporal signals in a submitted video.'],
  ['audio', 'Audio Verification', 'Assess recordings for synthetic voice or audio manipulation indicators.'],
];

function HeroVisual() {
  return <div className="hero-visual"><img src="/images/hero-home.png" alt="People reviewing content on a phone" /><div className="hero-visual-shade" /><span className="hero-label label-question">Question the source</span><span className="hero-label label-focus"><Icon name="lens" size={15} /> Look closer</span><div className="hero-focus-ring"><i /><i /></div><p>Illustrative scenario</p></div>;
}

export default function HomePage({ onNavigate }) {
  return <div className="page-enter"><section className="hero-section container"><div className="hero-copy"><span className="eyebrow">A clearer way to verify</span><h1>See through<br />the <em>lies.</em></h1><p>Verify text, images, videos, and audio with one unified content verification system. Understand the signals behind every result.</p><div className="hero-proof"><div className="avatar-stack"><img src="/images/workshop.png" alt="" /><img src="/images/public-information.png" alt="" /><img src="/images/hero-home.png" alt="" /></div><span>Clear, explainable verification<br />for real-world decisions</span></div><button className="button button-primary hero-cta" onClick={() => onNavigate('/verify/image')}>Start Verification <Icon name="arrow" size={17} /></button></div><HeroVisual /></section>
    <section className="capabilities container"><div className="section-heading centered"><span className="eyebrow">One lens, four ways to verify</span><h2>Start with the content you have.</h2><p>Each workflow is shaped around the signals the available analyzer can actually assess.</p></div><div className="capability-grid">{capabilities.map(([type, title, description]) => <button className="capability-card" key={type} onClick={() => onNavigate(`/verify/${type}`)}><span className="capability-icon"><Icon name={modalityConfig[type].icon} size={23} /></span><h3>{title}</h3><p>{description}</p><span className="card-link">Verify {modalityConfig[type].label} <Icon name="arrow" size={16} /></span></button>)}</div></section>
    <section className="editorial-section container"><div className="editorial-image image-phone"><img src="/images/hero-home.png" alt="A couple looking at content on a phone" /><span>Before you share</span></div><div className="editorial-copy"><span className="eyebrow">Understand before you react</span><h2>Digital content moves fast. Your decisions do not have to.</h2><p>Messages, recordings, images, and clips can make a claim before there is time to check it. TruthLens gives you a focused place to pause, inspect the available signals, and understand the assessment.</p><button className="text-link" onClick={() => onNavigate('/verify/text')}>Verify a message or claim <Icon name="arrow" size={16} /></button></div></section>
    <section className="editorial-section container reverse"><div className="editorial-image image-call"><img src="/images/video-call.png" alt="A person reviewing a video call" /><span>Illustrative scenario</span></div><div className="editorial-copy"><span className="eyebrow">Keep the context in view</span><h2>More than a verdict.</h2><p>A useful assessment needs to explain itself. Results keep the summary, risk level, and individual findings together, so you can see why the system reached its conclusion rather than relying on a single label.</p><button className="text-link" onClick={() => onNavigate('/verify/video')}>Explore video verification <Icon name="arrow" size={16} /></button></div></section>
    <section className="how-section" id="how-it-works"><div className="container how-layout"><div className="how-copy"><span className="eyebrow">How TruthLens works</span><h2>Verification in a few clear steps.</h2><div className="steps-list">{[['01', 'Upload your content', 'Choose an image, video, audio file, or paste text.'], ['02', 'Run verification', 'The matching available analyzer reviews the submitted content.'], ['03', 'Review the result', 'See the assessment, score, risk level, and findings.'], ['04', 'Understand the signals', 'Use the explanation to make a more informed next decision.']].map(([number, title, description]) => <article key={number}><span>{number}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></div><div className="how-visual"><img src="/images/workshop.png" alt="People discussing digital information" /><div className="how-overlay"><Icon name="lens" size={20} /><span>Pause. Check. Understand.</span></div></div></div></section>
    <section className="editorial-section container"><div className="editorial-image image-news"><img src="/images/public-information.png" alt="A journalist reviewing information" /><span>Public information</span></div><div className="editorial-copy"><span className="eyebrow">Built for everyday scrutiny</span><h2>Check across formats, in one calm workflow.</h2><p>Whether it is a public video, a questionable photo, a voice recording, or a message that asks you to act fast, the experience stays simple: submit, review, and understand.</p><button className="text-link" onClick={() => onNavigate('/about')}>Why TruthLens exists <Icon name="arrow" size={16} /></button></div></section>
    <section className="trust-section container"><div className="trust-card"><div className="trust-mark"><Icon name="lens" size={28} /></div><div><span className="eyebrow">A note on trust</span><h2>Clear about what the system can — and cannot — tell you.</h2></div><p>TruthLens is an automated, heuristic assessment. It surfaces detected signals and the explanation returned by the backend; it does not promise a forensic determination.</p></div></section>
    <section className="faq-section container" id="faq"><div className="section-heading centered"><span className="eyebrow">FAQ</span><h2>Questions worth asking.</h2><p>A little context before you begin.</p></div><FAQAccordion /></section>
    <section className="final-cta"><div className="container"><span className="eyebrow">Take a closer look</span><h2>Before you trust it,<br />run it through TruthLens.</h2><button className="button button-primary" onClick={() => onNavigate('/verify/image')}>Start Verifying <Icon name="arrow" size={17} /></button></div></section>
  </div>;
}
